src/Entity/Authorization.php
<?php

namespace App\Entity;

use App\Repository\AuthorizationRepository;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=AuthorizationRepository::class)
 */
class Authorization
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startDate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="authorizations")
     */
    private $validate_by;

    /**
     * @ORM\Column(type="float")
     */
    private $hours;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at=new \DateTimeImmutable("now");
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $statut): self
    {
        $this->status = $statut;

        return $this;
    }

    public function getValidateBy(): ?User
    {
        return $this->validate_by;
    }

    public function setValidateBy(?User $validate_by): self
    {
        $this->validate_by = $validate_by;

        return $this;
    }

    public function getHours(): ?float
    {
        return $this->hours;
    }

    public function setHours(float $hours): self
    {
        $this->hours = $hours;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Gets triggered only on insert

     * @ORM\PrePersist
     */
    public function onPrePersist()
    {
        $this->created_at = new \DateTimeImmutable("now");
    }
}

src/Entity/HolidayRequest.php
<?php

namespace App\Entity;

use App\Repository\HolidayRequestRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=HolidayRequestRepository::class)
 */
class HolidayRequest
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThan("today",message="le jour de début doit être supérieur à aujourd'hui")
     */
    private $startDate;

    /**
     * @ORM\Column(type="date")
     * @Assert\Expression(
     *     "this.getStartDate() < this.getEndDate()",
     *      message="La date fin ne doit pas être antérieure à la date début")
     */
    private $endDate;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="holidayRequests")
     */
    private $user_id;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="test")
     */
    private $validby;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $description;

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getNbjours()
    {
        return $this->nbjours;
    }

    /**
     * @param mixed $nbjours
     */
    public function setNbjours($nbjours): void
    {
        $this->nbjours = $nbjours;
    }
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbjours;


    public function __construct()
    {
        $this->created_at=new \DateTimeImmutable("now");
        $this->updated_at=new \DateTimeImmutable("now");
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $create_at): self
    {
        $this->created_at = $create_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Gets triggered only on insert

     * @ORM\PrePersist
     */
    public function onPrePersist()
    {
        $this->created_at = new \DateTimeImmutable("now");
    }

    /**
     * Gets triggered every time on update

     * @ORM\PreUpdate
     */
    public function onPreUpdate()
    {
        $this->updated_at = new \DateTimeImmutable("now");
    }

    public function getValidby(): ?User
    {
        return $this->validby;
    }

    public function setValidby(?User $validby): self
    {
        $this->validby = $validby;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(?int $status): self
    {
        $this->status = $status;

        return $this;
    }



}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;
    /**
     * @ORM\Column(type="string", length=180, nullable=true)
     */
    private $departement;
    /**
     * @ORM\Column(type="string", length=180, nullable=true)
     */
    private $adresse;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $soldecong;

    /**
     * @return mixed
     */
    public function getSoldecong()
    {
        return $this->soldecong;
    }

    /**
     * @param mixed $soldecong
     */
    public function setSoldecong($soldecong): void
    {
        $this->soldecong = $soldecong;
    }

    /**
     * @return mixed
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * @param mixed $adresse
     */
    public function setAdresse($adresse): void
    {
        $this->adresse = $adresse;
    }


    /**
     * @return mixed
     */
    public function getDepartement()
    {
        return $this->departement;
    }

    /**
     * @param mixed $departement
     */
    public function setDepartement($departement): void
    {
        $this->departement = $departement;
    }

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    private $type = [];

    /**
     * @ORM\OneToMany(targetEntity=HolidayRequest::class, mappedBy="user_id")
     */
    private $holidayRequests;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FirstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $LastName;

    /**
     * @ORM\ManyToOne(targetEntity=ValidatedHolidayBy::class, inversedBy="user_id")
     */
    private $validatedHolidayBy;

    /**
     * @ORM\OneToMany(targetEntity=Authorization::class, mappedBy="validate_by")
     */
    private $authorizations;

    /**
     * @ORM\OneToMany(targetEntity=HolidayRequest::class, mappedBy="validby")
     */
    private $test;

    public function __construct()
    {
        $this->holidayRequests = new ArrayCollection();
        $this->authorizations = new ArrayCollection();
        $this->test = new ArrayCollection();
        $this->soldecong=21;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getType(): ?array
    {
        return $this->type;
    }

    public function setType(array $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|HolidayRequest[]
     */
    public function getHolidayRequests(): Collection
    {
        return $this->holidayRequests;
    }

    public function addHolidayRequest(HolidayRequest $holidayRequest): self
    {
        if (!$this->holidayRequests->contains($holidayRequest)) {
            $this->holidayRequests[] = $holidayRequest;
            $holidayRequest->setUserId($this);
        }

        return $this;
    }

    public function removeHolidayRequest(HolidayRequest $holidayRequest): self
    {
        if ($this->holidayRequests->removeElement($holidayRequest)) {
            // set the owning side to null (unless already changed)
            if ($holidayRequest->getUserId() === $this) {
                $holidayRequest->setUserId(null);
            }
        }

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getValidatedHolidayBy(): ?ValidatedHolidayBy
    {
        return $this->validatedHolidayBy;
    }

    public function setValidatedHolidayBy(?ValidatedHolidayBy $validatedHolidayBy): self
    {
        $this->validatedHolidayBy = $validatedHolidayBy;

        return $this;
    }

    /**
     * @return Collection|Authorization[]
     */
    public function getAuthorizations(): Collection
    {
        return $this->authorizations;
    }

    public function addAuthorization(Authorization $authorization): self
    {
        if (!$this->authorizations->contains($authorization)) {
            $this->authorizations[] = $authorization;
            $authorization->setValidateBy($this);
        }

        return $this;
    }

    public function removeAuthorization(Authorization $authorization): self
    {
        if ($this->authorizations->removeElement($authorization)) {
            // set the owning side to null (unless already changed)
            if ($authorization->getValidateBy() === $this) {
                $authorization->setValidateBy(null);
            }
        }

        return $this;
    }
}

templates/bashboard/responsable/_modal.html.twig
{# templates/user/notifications.html.twig #}
<h1>Hello {{ user_first_name }}!</h1>
<p>You have {{ notifications|length }} new notifications.</p>

templates/bashboard/responsable/index.html.twig
{% extends 'bashboard/base.html.twig' %}

{% block title %}Hello ResponsableController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/var/www/html/assurence/src/Controller/ResponsableController.php'|file_link(0) }}">src/Controller/ResponsableController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/var/www/html/assurence/templates/responsable/index.html.twig'|file_link(0) }}">templates/responsable/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/bashboard/responsable/index2.html.twig
{% extends 'bashboard/base.html.twig' %}
{% block body %}
    <div class="card text-center" style="width: 30rem;">
<div class="card-body">
    {{ form_start(form) }}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <div class="form-group">
        {{ form_row(form.description, {'attr': {'class': 'form-control input-default'}}) }}
    </div>
    {{ form_end(form) }}
</div>
    </div>
{% endblock %}

templates/bashboard/responsable/validation.authorization.html.twig
{% extends 'bashboard/base.html.twig' %}

{% block title %}Ajout {% endblock %}

{% block body %}
  <div class="card">
    <div class="card-title">
      <h4>Validation des autorisations </h4>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>Nom & Prénom</th>
            <th>Du</th>
            <th>Nombre de jours</th>
            <th>Date de la demande</th>
            <th>Etat de validation</th>
            {% if not is_granted('ROLE_ADMIN') %}
              <th style="text-align: center;">Action</th>
            {% endif %}
          </tr>
          </thead>
          <tbody>
          {% for l in list %}
            <tr>
              <th scope="row"> {{ l.user.firstName }} {{ l.user.lastName }}</th>
              <td>{{ l.startDate | date('d-m-Y') }}</td>
              <td>{{ autorisation[l.hours] }}</td>
              <td>{{ l.createdAt |date('d-m-Y') }}</td>
              <td>
                {% if l.status == 1 %}
                  <span class="badge badge-success">
                      Validé
                  </span>
                {% elseif l.status == -1 %}
                  <span class="badge badge-danger">
                  Rejetée
                </span>
                {% else %}
                  <span class="badge badge-primary">
                      encours
                        </span>
                {% endif %}

              </td>
              {% if not is_granted('ROLE_ADMIN') %}
                <td>
                  {% if l.validateBy is null %}
                    <a href="{{ path('autorisation_validate_request', { 'id': l.id, 'action': 'valide', 'route': routeName }) }}"
                       class="btn btn-info"
                       onclick="return confirm('Êtes-vous sûr?')">Validé</a>
                    <a href="{{ path('autorisation_validate_request', { 'id': l.id, 'action': 'annuler', 'route': routeName }) }}"
                       class="btn btn-red"
                       onclick="return confirm('Êtes-vous sûr?')">Annuler</a>
                  {% else %}
                    -
                  {% endif %}
                </td>
              {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

templates/bashboard/responsable/validation.html.twig
{% extends 'bashboard/base.html.twig' %}

{% block title %}Validation des congés{% endblock %}

{% block body %}
  <div class="card">
    <div class="card-title">
      <h4>Validation des congés </h4>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>Nom & Prénom</th>
            <th>Du</th>
            <th>Au</th>
            <th>Nombre de jours</th>
            <th>Date de la demande</th>

            <th>statut</th>
            <th>description</th>
            {% if not is_granted('ROLE_ADMIN') %}
              <th style=" text-align: center;">Action</th>
            {% endif %}


          </tr>
          </thead>
          <tbody>
          {% for l in list %}
            {% set difference = date(l.startDate).diff(date(l.endDate)).format('%a') %}
            <tr>
              <th scope="row">{{ l.userId.firstName  }} {{ l.userId.lastName  }}</th>
              <td>{{ l.startDate | date('d-m-Y') }}</td>
              <td>{{ l.endDate | date('d-m-Y') }}</td>
              <td style=" text-align: center;   ">{{ l.nbjours}}</td>
              <td>{{ l.createdAt |date('d-m-Y') }}</td>
              <td>
                {% if  l.status == 1 %}
                  <span class="badge badge-success">
                      Validé
                  </span>
                {% elseif l.status == -1 %}
                  <span class="badge badge-danger">
                  Rejetée
                </span>
                {% else %}
                  <span class="badge badge-primary">
                      encours
                  </span>
                {% endif %}
              </td>
              <td>
                {{ l.description }}
              </td>
              <!--<td>
                {% if not l.validby is null %}
                  Validation Responsable({{ l.validby.firstName }})
                {% else %}
                  -
                {% endif %}

              </td>-->
              {% if not is_granted('ROLE_ADMIN') %}
                <td>
                  {% if not l.validby is null %}
                    -
                  {% else %}

                    <a href="{{ path('confirm_request', { 'id': l.id , 'action': 'valide', 'route': routeName }) }}"
                       class="btn btn-info"
                       onclick="return confirm('Êtes-vous sûr?')">Valider</a>
                    <a href="{{ path('confirm_request', { 'id': l.id, 'action': 'annuler', 'route': routeName }) }}"
                       class="btn btn-red"
                       onclick="return confirm('Êtes-vous sûr?')">Annuler</a>











                      {% endif %}




                </td>
              {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
        {{ knp_pagination_render(list) }}
      </div>
    </div>
  </div>
{% endblock %}